insert into article (title) values ('Blueberry Muffin Mix');
insert into article (title) values ('Luxury Bathrobe');
insert into article (title) values ('Portable Solar Generator');
insert into article (title) values ('Toasted Coconut Granola');
insert into article (title) values ('Organic Almond Flour');
insert into article (title) values ('Greek Yogurt');
insert into article (title) values ('Digital Camera');
insert into article (title) values ('Maple Oatmeal');
insert into article (title) values ('Foldable Yoga Mat');
insert into article (title) values ('Tomatillo Salsa');